### ISSUE TITLE
Verification system not working in prod

### ISSUE THREAD

**Issue by YT-GameWorks** [select-studios/Select-Launcher#6]
There are currently 2 problems with the verification system:
1. Wrong email address
2. Wrong certificate so can't open link
3. Button in email non functional.

**Comment by YT-GameWorks** [comment]
the first issue refers to it using your email address and not the select studios noreply email.
3rd issue refers to:

![image](https://user-images.githubusercontent.com/39207327/218662247-84c0df9b-09a2-446c-aca1-3453b430c3e3.png)

**Comment by YT-GameWorks** [comment]
The last issue only occurs in outlook though.

**Comment by Mellurboo** [comment]
This issue is caused by outlooks verification system when it comes to handling links, they don't usually trust links without a email domain

**Comment by Mellurboo** [comment]
I was wrong
