### ISSUE TITLE
window scaling up doesn't work

### ISSUE THREAD

**Issue by Mellurboo** [select-studios/Select-Launcher#7]
pressing CTRL+ Minus reduces the UI scale perfectly
pressing CTRL+ Plus **Does not** increase the UI scale

this is just a janky thing it doesn't really matter but whatever it'd be nice if there was a fix but I don't really care.
(basically if u cant fix it in 5 mins its not worth it so don't worry)

**Comment by Mellurboo** [comment]
Found it :)
**CTRL + Minus** - to scale down
**CTRL + Shift + Plus** - to scale back up

**Comment by YT-GameWorks** [comment]
I'll update the menu context to display the same :)
