### ISSUE TITLE
UI Loading before the User data

### ISSUE THREAD

**Issue by Mellurboo** [select-studios/Select-Launcher#8]
sometimes the UI will load before the user, we're not sure why or how this happens but it causes the username to disappear and essentially act as if they are logged out, its not a major issue but should be fixed soon

**Comment by Aktindo** [comment]
The problem occurs whenever there is an error in the expiration of the old access token a user might be having. Although the error is inconsistent, with the update in the token handler, it should be fixed in the latest commit.

Closing the issue for now.
