### ISSUE TITLE
Spacing from Dev to Prod is a bit weird

### ISSUE THREAD

**Issue by Mellurboo** [select-studios/Select-Launcher#9]
the Development version seems to have much nicer spacing than the Prod build. 
![image](https://user-images.githubusercontent.com/102391892/218337723-6d839e31-dd1e-49d2-af6a-6dbcb3e47754.png)
![image](https://user-images.githubusercontent.com/102391892/218337765-7ee7cb8d-e5ab-4465-9df1-b01f80a64433.png)

this is probably an easy fix

**Comment by Aktindo** [comment]
Fixed.
